#!/bin/bash
PYVER=`python -V 2>&1  | awk '{ print $2 }'  |  grep -o "[[:digit:]+]\.[[:digit:]]" `
#echo $PYVER
RPMEXE=/usr/lib/python$PYVER/site-packages/certify/certify-binary.py
HOMEEXE=~/lib/python/certify/certify-binary.py

if [ -f $RPMEXE ]; then
	python /usr/lib/python$PYVER/site-packages/certify/certify-binary.py $*
elif [ -f $HOMEEXE ]; then
    export PYTHONPATH=~/lib/python
    python $HOMEEXE $*
else
	echo "No suitable Certify executable found."
fi



